openapi: '3.0.0'
info:
  version: 1.0.0
  title: タスクリストAPI

paths:
  /tasks:
    get:
      summary: タスク一覧取得
      description: タスクの一覧を取得します。ソートは作成日時の昇順です。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '500':
          description: Internal Server Error
    post:
      summary: タスク作成
      description: 新しいタスクを作成します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /tasks/{id}:
    get:
      summary: タスク取得
      description: IDで指定されたタスクを取得します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    put:
      summary: タスク更新
      description: タスクの詳細情報を更新します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    patch:
      summary: タスクの完了状態を変更
      description: タスクの完了状態を変更します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                completed:
                  type: boolean
                  description: タスクが完了したかどうか。
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    delete:
      summary: タスク削除
      description: タスクを削除します。
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: タスクの一意の識別子(UUID)。
          example: 'f0f8f5a0-309d-11ec-8d3d-0242ac130003'
        title:
          type: string
          description: タスクのタイトル。
          example: '買い物する'
        completed:
          type: boolean
          description: タスクが完了したかどうか。
          example: false
        createdAt:
          type: integer
          format: int64
          description: タスクの作成日時（UNIXタイムスタンプ）。
          example: 1678345600
        updatedAt:
          type: integer
          format: int64
          description: タスクの最終更新日時（UNIXタイムスタンプ）。
          example: 1678349200
